config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :basvurans

  resources :gonullus

  resources :giris_forms

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/giris_forms_controller.rb
class GirisFormsController < ApplicationController
  before_action :set_giris_form, only: [:show, :edit, :update, :destroy]

  # GET /giris_forms
  # GET /giris_forms.json
  def index
    @giris_forms = GirisForm.all
  end

  # GET /giris_forms/1
  # GET /giris_forms/1.json
  def show
  end

  # GET /giris_forms/new
  def new
    @giris_form = GirisForm.new
  end

  # GET /giris_forms/1/edit
  def edit
  end

  # POST /giris_forms
  # POST /giris_forms.json
  def create
    @giris_form = GirisForm.new(giris_form_params)

    respond_to do |format|
      if @giris_form.save
        format.html { redirect_to @giris_form, notice: 'Giris form was successfully created.' }
        format.json { render :show, status: :created, location: @giris_form }
      else
        format.html { render :new }
        format.json { render json: @giris_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /giris_forms/1
  # PATCH/PUT /giris_forms/1.json
  def update
    respond_to do |format|
      if @giris_form.update(giris_form_params)
        format.html { redirect_to @giris_form, notice: 'Giris form was successfully updated.' }
        format.json { render :show, status: :ok, location: @giris_form }
      else
        format.html { render :edit }
        format.json { render json: @giris_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /giris_forms/1
  # DELETE /giris_forms/1.json
  def destroy
    @giris_form.destroy
    respond_to do |format|
      format.html { redirect_to giris_forms_url, notice: 'Giris form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_giris_form
      @giris_form = GirisForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def giris_form_params
      params.require(:giris_form).permit(:ilk_basvuru_tarihi, :mc_destek_aliyor, :iletisime_gecen, :iletisime_gecme_yolu, :notlar)
    end
end

app/helpers/giris_forms_helper.rb
module GirisFormsHelper
end

app/views/giris_forms/_form.html.erb
<%= form_for @giris_form, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :ilk_basvuru_tarihi, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.date_select :ilk_basvuru_tarihi, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mc_destek_aliyor, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :mc_destek_aliyor, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :iletisime_gecen, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :iletisime_gecen, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :iletisime_gecme_yolu, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :iletisime_gecme_yolu, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :notlar, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :notlar, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  giris_forms_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/giris_forms/edit.html.erb
<%- model_class = GirisForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => GirisForm %></h1>
</div>
<%= render :partial => 'form' %>

app/views/giris_forms/index.html.erb
<%- model_class = GirisForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => GirisForm %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:ilk_basvuru_tarihi) %></th>
      <th><%= model_class.human_attribute_name(:mc_destek_aliyor) %></th>
      <th><%= model_class.human_attribute_name(:iletisime_gecen) %></th>
      <th><%= model_class.human_attribute_name(:iletisime_gecme_yolu) %></th>
      <th><%= model_class.human_attribute_name(:notlar) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @giris_forms.each do |giris_form| %>
      <tr>
        <td><%= giris_form.id %></td>
        <td><%= giris_form.ilk_basvuru_tarihi %></td>
        <td><%= giris_form.mc_destek_aliyor %></td>
        <td><%= giris_form.iletisime_gecen %></td>
        <td><%= giris_form.iletisime_gecme_yolu %></td>
        <td><%= giris_form.notlar %></td>
        <td><%=l giris_form.created_at, format: :long %></td>
        <td>
          <%= link_to giris_form_path(giris_form), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to giris_form_path(giris_form), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_giris_form_path,
            :class => 'btn btn-primary' %>

app/views/giris_forms/new.html.erb
<%- model_class = GirisForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => GirisForm %></h1>
</div>
<%= render :partial => 'form' %>

app/views/giris_forms/show.html.erb
<%- model_class = GirisForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => GirisForm %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ilk_basvuru_tarihi) %></dt>
      <dd><pre class="prettyprint"><%= @giris_form.ilk_basvuru_tarihi %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mc_destek_aliyor) %></dt>
      <dd><pre class="prettyprint"><%= @giris_form.mc_destek_aliyor %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:iletisime_gecen) %></dt>
      <dd><pre class="prettyprint"><%= @giris_form.iletisime_gecen %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:iletisime_gecme_yolu) %></dt>
      <dd><pre class="prettyprint"><%= @giris_form.iletisime_gecme_yolu %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:notlar) %></dt>
      <dd><pre class="prettyprint"><%= @giris_form.notlar %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              giris_forms_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_giris_form_path(@giris_form), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              giris_form_path(@giris_form),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>