config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :basvurans

  resources :gonullus

  resources :giris_forms

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/basvuran.rb
class Basvuran < ActiveRecord::Base
  belongs_to :gonullu
  belongs_to :user
  belongs_to :giris_form
  validates_formatting_of :telefon, using: :us_phone
  validates_formatting_of :mail, using: :email
end

app/controllers/basvurans_controller.rb
class BasvuransController < ApplicationController
  before_action :set_basvuran, only: [:show, :edit, :update, :destroy]

  # GET /basvurans
  # GET /basvurans.json
  def index
    @basvurans = Basvuran.all
  end

  # GET /basvurans/1
  # GET /basvurans/1.json
  def show
  end

  # GET /basvurans/new
  def new
    @basvuran = Basvuran.new
  end

  # GET /basvurans/1/edit
  def edit
  end

  # POST /basvurans
  # POST /basvurans.json
  def create
    @basvuran = Basvuran.new(basvuran_params)

    respond_to do |format|
      if @basvuran.save
        format.html { redirect_to @basvuran, notice: 'Basvuran was successfully created.' }
        format.json { render :show, status: :created, location: @basvuran }
      else
        format.html { render :new }
        format.json { render json: @basvuran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /basvurans/1
  # PATCH/PUT /basvurans/1.json
  def update
    respond_to do |format|
      if @basvuran.update(basvuran_params)
        format.html { redirect_to @basvuran, notice: 'Basvuran was successfully updated.' }
        format.json { render :show, status: :ok, location: @basvuran }
      else
        format.html { render :edit }
        format.json { render json: @basvuran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basvurans/1
  # DELETE /basvurans/1.json
  def destroy
    @basvuran.destroy
    respond_to do |format|
      format.html { redirect_to basvurans_url, notice: 'Basvuran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_basvuran
      @basvuran = Basvuran.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def basvuran_params
      params.require(:basvuran).permit(:isim, :soyisim, :basvuran_kod, :telefon, :mail, :gonullu_id, :user_id, :giris_form_id)
    end
end

app/helpers/basvurans_helper.rb
module BasvuransHelper
end

app/views/basvurans/_form.html.erb
<%= form_for @basvuran, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :isim, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :isim, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :soyisim, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :soyisim, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :basvuran_kod, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :basvuran_kod, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefon, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :telefon, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mail, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.email_field :mail, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  basvurans_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/basvurans/edit.html.erb
<%- model_class = Basvuran -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Basvuran %></h1>
</div>
<%= render :partial => 'form' %>

app/views/basvurans/index.html.erb
<%- model_class = Basvuran -%>
<div class="page-header">
  <h1><%=t '.title', :default => Basvuran %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:isim) %></th>
      <th><%= model_class.human_attribute_name(:soyisim) %></th>
      <th><%= model_class.human_attribute_name(:basvuran_kod) %></th>
      <th><%= model_class.human_attribute_name(:telefon) %></th>
      <th><%= model_class.human_attribute_name(:mail) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @basvurans.each do |basvuran| %>
      <tr>
        <td><%= basvuran.id %></td>
        <td><%= basvuran.isim %></td>
        <td><%= basvuran.soyisim %></td>
        <td><%= basvuran.basvuran_kod %></td>
        <td><%= basvuran.telefon %></td>
        <td><%= basvuran.mail %></td>
        <td><%=l basvuran.created_at, format: :long %></td>
        <td>
          <%= link_to basvuran_path(basvuran), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to basvuran_path(basvuran), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_basvuran_path,
            :class => 'btn btn-primary' %>

app/views/basvurans/new.html.erb
<%- model_class = Basvuran -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Basvuran %></h1>
</div>
<%= render :partial => 'form' %>

app/views/basvurans/show.html.erb
<%- model_class = Basvuran -%>
<div class="page-header">
  <h1><%=t '.title', :default => Basvuran %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:isim) %></dt>
      <dd><pre class="prettyprint"><%= @basvuran.isim %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:soyisim) %></dt>
      <dd><pre class="prettyprint"><%= @basvuran.soyisim %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:basvuran_kod) %></dt>
      <dd><pre class="prettyprint"><%= @basvuran.basvuran_kod %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:telefon) %></dt>
      <dd><pre class="prettyprint"><%= @basvuran.telefon %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:mail) %></dt>
      <dd><pre class="prettyprint"><%= @basvuran.mail %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              basvurans_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_basvuran_path(@basvuran), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              basvuran_path(@basvuran),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>