config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :basvurans

  resources :gonullus

  resources :giris_forms

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/gonullu.rb
class Gonullu < ActiveRecord::Base
  has_many :basvurans
end

app/controllers/gonullus_controller.rb
class GonullusController < ApplicationController
  before_action :set_gonullu, only: [:show, :edit, :update, :destroy]

  # GET /gonullus
  # GET /gonullus.json
  def index
    @gonullus = Gonullu.all
  end

  # GET /gonullus/1
  # GET /gonullus/1.json
  def show
  end

  # GET /gonullus/new
  def new
    @gonullu = Gonullu.new
  end

  # GET /gonullus/1/edit
  def edit
  end

  # POST /gonullus
  # POST /gonullus.json
  def create
    @gonullu = Gonullu.new(gonullu_params)

    respond_to do |format|
      if @gonullu.save
        format.html { redirect_to @gonullu, notice: 'Gonullu was successfully created.' }
        format.json { render :show, status: :created, location: @gonullu }
      else
        format.html { render :new }
        format.json { render json: @gonullu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gonullus/1
  # PATCH/PUT /gonullus/1.json
  def update
    respond_to do |format|
      if @gonullu.update(gonullu_params)
        format.html { redirect_to @gonullu, notice: 'Gonullu was successfully updated.' }
        format.json { render :show, status: :ok, location: @gonullu }
      else
        format.html { render :edit }
        format.json { render json: @gonullu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gonullus/1
  # DELETE /gonullus/1.json
  def destroy
    @gonullu.destroy
    respond_to do |format|
      format.html { redirect_to gonullus_url, notice: 'Gonullu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gonullu
      @gonullu = Gonullu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gonullu_params
      params.require(:gonullu).permit(:isim)
    end
end

app/helpers/gonullus_helper.rb
module GonullusHelper
end

app/views/gonullus/_form.html.erb
<%= form_for @gonullu, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :isim, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :isim, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  gonullus_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/gonullus/edit.html.erb
<%- model_class = Gonullu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Gonullu %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gonullus/index.html.erb
<%- model_class = Gonullu -%>
<div class="page-header">
  <h1><%=t '.title', :default => Gonullu %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:isim) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gonullus.each do |gonullu| %>
      <tr>
        <td><%= gonullu.id %></td>
        <td><%= gonullu.isim %></td>
        <td><%=l gonullu.created_at, format: :long %></td>
        <td>
          <%= link_to gonullu_path(gonullu), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to gonullu_path(gonullu), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gonullu_path,
            :class => 'btn btn-primary' %>

app/views/gonullus/new.html.erb
<%- model_class = Gonullu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Gonullu %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gonullus/show.html.erb
<%- model_class = Gonullu -%>
<div class="page-header">
  <h1><%=t '.title', :default => Gonullu %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:isim) %></dt>
      <dd><pre class="prettyprint"><%= @gonullu.isim %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gonullus_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gonullu_path(@gonullu), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gonullu_path(@gonullu),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>